// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export interface ErrorResponse {
	errorMessage: string;
}
export interface AuthRequest {
	username: string;
}
export interface AuthResponse {
	token?: string;
	ErrorResponse: ErrorResponse;
}
export interface Project {
	id: number /* int */;
	name: string;
	description: string;
}
export interface DashboardResponse {
	projects: Project[];
}
